services:
  - type: web
    name: course-reg-system
    rootDir: Course-Registration-System-SpringBoot
    runtime: java
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: course-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: course-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: course-db
          property: password
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/*.jar

databases:
  - name: course-db
    databaseName: course_reg_sym
    user: course_user
